frontend/urls.py
# Author:   Cory Nance <canance@coastal.edu>
# Revision: 6 February 2016
#
# Copyright 2016 Coastal Carolina University
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^cast/', views.cast, name='cast'),
    url(r'^change/', views.change, name='change'),
    url(r'^create_device/', views.create_device, name="create_device"),
    url(r'^create_device_group', views.create_device_group, name='create_device_group'),
    url(r'^devices/', views.devices, name='devices'),
    url(r'^device_groups/', views.device_groups, name='device_groups'),
    url(r'^edit_device/(?P<dev>\d+)/$', views.edit_device, name='edit_device'),
    url(r'^slideshows/', views.slideshows, name="slideshows"),
    url(r'^slideshow/(?P<name>.*)/$', views.get_slideshow, name="slideshow"),
    url(r'^slideshow_json/(?P<name>.*)/$', views.get_slideshow_json, name="slideshow_json"),
    url(r'^streams/', views.streams, name="streams"),
    url(r'^create_slideshow/', views.create_slideshow, name="create_slideshow"),
    url(r'^create_stream/', views.create_stream, name="create_stream"),
    url(r'^delete_slideshow/(?P<name>.*)/$', views.delete_slideshow, name="delete_slideshow"),
    url(r'^edit_slideshow/(?P<name>.*)/$', views.edit_slideshow, name='edit_slideshow'),
    url(r'^delete_stream/(?P<name>.*)/$', views.delete_stream, name="delete_stream"),
    url(r'^edit_stream/(?P<name>.*)/$', views.edit_stream, name='edit_stream'),
    url(r'^edit_device_group/(?P<grp>\d+)/$', views.edit_device_group, name='edit_device_group'),
]

signpi/urls.py
# Author:   Cory Nance <canance@coastal.edu>
# Revision: 6 February 2016
#
# Copyright 2016 Coastal Carolina University
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""signpi URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from frontend import views as frontend_views
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^frontend/', include('frontend.urls', namespace='frontend')),
    url(r'^backend/', include('backend.urls', namespace='backend')),
    url(r'^login$', auth_views.login),
    url(r'^logout/$', auth_views.logout),
    url(r'^$', frontend_views.index),
]

frontend/models.py
from django.db import models

frontend/forms.py
# Author:   Cory Nance <canance@coastal.edu>
# Revision: 7 February 2016
#
# Copyright 2016 Coastal Carolina University
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django import forms
from django.forms import ModelForm, Form
from backend.models import Group, Device, Stream


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = '__all__'


class DeviceForm(ModelForm):
    class Meta:
        model = Device
        fields = '__all__'
        exclude = ("configuration",)


class SlideshowForm(Form):
    name = forms.CharField(label="Name", max_length=100)
    desc = forms.CharField(label="Description", max_length=255)
    url = forms.CharField(label="PDF URL", max_length=255)


class StreamForm(ModelForm):
    class Meta:
        model = Stream
        fields = '__all__'

frontend/views.py
# Author:   Cory Nance <canance@coastal.edu>
# Revision: 6 February 2016
#
# Copyright 2016 Coastal Carolina University
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from backend.models import Stream, Device, Group
from .forms import DeviceForm, GroupForm, SlideshowForm, StreamForm
from . import slideshow
import json

@login_required()
def index(request):
    devices = len(Device.objects.all())
    groups = len(Group.objects.all())
    streams = len(Stream.objects.all())

    context = {
        'devices': devices,
        'streams': streams,
        'groups': groups,
    }
    return render(request, 'frontend/index.html', context)

@login_required()
def change(request):
    device_ids = request.POST.getlist('devices[]')  # device ids
    group_ids = request.POST.getlist('groups[]')  # group ids
    config = request.POST['config']  # config name

    for device_id in device_ids:
        device = get_object_or_404(Device, pk=device_id)
        device.configuration = config
        device.save()

    for group_id in group_ids:
        group = get_object_or_404(Group, pk=group_id)
        for device in group.devices.all():
            device.configuration = config
            device.save()

    return HttpResponseRedirect('/frontend/')


@login_required()
def cast(request):
    devices = Device.objects.order_by('name')
    groups = Group.objects.order_by('name')
    streams = Stream.objects.order_by('name')
    slideshows = slideshow.list_slideshows()

    castable = len(devices) > 0 and (len(streams) > 0 or len(slideshows) > 0)

    context = {
        'devices': devices,
        'groups': groups,
        'streams': streams,
        'slideshows': slideshows,
        'castable': castable,
    }
    return render(request, 'frontend/cast.html', context)


@login_required()
def device_groups(request):
    groups = Group.objects.order_by('name')

    context = {
        'groups': groups,
        'size': len(groups),
    }
    return render(request, 'frontend/device_groups.html', context)


@login_required()
def create_device_group(request):
    if request.method == 'POST':
        form = GroupForm(request.POST, label_suffix='')
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/frontend/device_groups')
    else:
        form = GroupForm(label_suffix='')

    context = {
        'form': form,
    }
    return render(request, 'frontend/create_device_group.html', context)


@login_required()
def edit_device_group(request, grp):
    group = Group.objects.get(pk=grp)

    if request.method == 'POST':
        form = GroupForm(request.POST, instance=group)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/frontend/device_groups')
    else:
        form = GroupForm(instance=group, label_suffix='')
        context = {
            'form': form,
        }
        return render(request, 'frontend/edit_device_group.html', context)


@login_required()
def devices(request):
    devs = Device.objects.order_by('name')
    context = {
        'devices': devs,
        'size': len(devs),
    }
    return render(request, 'frontend/devices.html', context)


@login_required()
def edit_device(request, dev):
    dev = Device.objects.get(pk=dev)

    if request.method == 'POST':
        form = DeviceForm(request.POST, instance=dev)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/frontend/devices')
    else:
        form = DeviceForm(instance=dev, label_suffix='')
        context = {
            'form': form,
        }
        return render(request, 'frontend/edit_device.html', context)
    return HttpResponseRedirect('/frontend/devices')

@login_required()
def create_device(request):
    if request.method == 'POST':
        form = DeviceForm(request.POST, label_suffix='')
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/frontend/devices')
    else:
        form = DeviceForm(label_suffix='')

    context = {
        'form': form,
    }
    return render(request, 'frontend/create_device.html', context)


@login_required()
def slideshows(request):
    slides = slideshow.list_slideshows()
    context = {
        'slides': slides,
        'size': len(slides),
    }
    return render(request, 'frontend/slideshows.html', context)


@login_required()
def edit_slideshow(request, name):
    if request.method == 'POST':
        form = SlideshowForm(request.POST)
        if form.is_valid():
            slideshow.delete_slideshow(name)
            slideshow.create_slideshow(form.data['name'], form.data['desc'], form.data['url'])
            return HttpResponseRedirect('/frontend/slideshows')
    else:
        desc, url = slideshow.get_info(name)
        data = {
            'name': name,
            'url': url,
            'desc': desc,
            }
        form = SlideshowForm(data)
        context = {
            'form': form,
            'name': name,
        }
        return render(request, 'frontend/edit_slideshow.html', context)


@login_required()
def create_slideshow(request):
    if request.method == 'POST':
        form = SlideshowForm(request.POST)
        if form.is_valid():
            slideshow.create_slideshow(form.data['name'], form.data['desc'], form.data['url'])
            return HttpResponseRedirect('/frontend/slideshows')
    else:
        form = SlideshowForm()

    context = {
        'form': form,
    }
    return render(request, 'frontend/create_slideshow.html', context)


def get_slideshow(request, name):

    url = request.build_absolute_uri(reverse('frontend:slideshow_json', kwargs={'name': name}))
    context = {
        'url': url,
    }
    return render(request, 'frontend/slideshow.html', context)


def get_slideshow_json(request, name):
    slide_names = slideshow.list_slides(name)
    slides = ['/static/frontend/web/%s/slides/%s' % (name, slide) for slide in slide_names]

    slide_json = {
        'slides': []
    }

    for num, slide in enumerate(slides):
        slide_json['slide_' + str(num)] = {
            'image': slide,
            'time': 10,
        }
        slide_json['slides'].append('slide_' + str(num))

    return HttpResponse(json.dumps(slide_json), content_type="application/json")


@login_required()
def delete_slideshow(request, name):
    slideshow.delete_slideshow(name)
    return HttpResponseRedirect('/frontend/slideshows')


@login_required()
def streams(request):
    streams = Stream.objects.order_by('name')
    context = {
        'streams': streams,
        'size': len(streams),
    }
    return render(request, 'frontend/streams.html', context)


@login_required()
def create_stream(request):
    if request.method == 'POST':
        form = StreamForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/frontend/streams')
    else:
        form = StreamForm(label_suffix='')

    context = {
        'form': form,
    }
    return render(request, 'frontend/create_stream.html', context)


@login_required()
def edit_stream(request, name):
    if request.method == 'POST':
        form = StreamForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/frontend/streams')
    else:
        stream = Stream.objects.get(name=name)
        form = StreamForm(instance=stream, label_suffix='')
        context = {
            'form': form,
            'name': name,
        }
        return render(request, 'frontend/edit_stream.html', context)


@login_required()
def delete_stream(request, name):
    stream = Stream.objects.get(name=name)
    stream.delete()
    return render(request, 'frontend/streams.html')

templates/frontend/cast.html
{% extends "frontend/base.html" %}

{% block content %}
    <h1>Cast</h1>
    <br/>
    {% if castable %}
    <form id="change" action="{% url 'frontend:change' %}" method="post">

        {% csrf_token %}
        <h3>Destination</h3>
        <div id="accordion">
            <h3>Device Groups</h3>
            <div>
                <select multiple="multiple" name="groups[]" id="group_select">
                    {% for group in groups %}
                        <option value="{{ group.id }}">{{ group.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <h3>Devices</h3>
            <div>
                <select multiple="multiple" name="devices[]" id="device_select">
                    {% for device in devices %}
                        <option value="{{ device.id }}">{{ device.name }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <br/><br/>
        <h3>Configuration</h3>
        <br/>

        <div id="configuration_select">
        <h4>Streams</h4>
            {% for stream in streams %}
                <input type="radio" name="config" id="stream:{{ stream.name }}" value="stream:{{ stream.name }}"/>
                <label for="stream:{{ stream.name }}">{{ stream.name }}</label>
            {% endfor %}
        <h4>Slideshows</h4>
            {% for slideshow in slideshows %}
                <input type="radio" name="config" id="slideshow:{{ slideshow }}" value="slideshow:{{ slideshow }}"/>
                <label for="slideshow:{{ slideshow }}">{{ slideshow }}</label>
            {% endfor %}
        </div>
        <br/>
        <br/>
        <input type="submit" value="Cast"/>
    </form>
    {% else %}
    <p>You need to add some devices or slideshow/streams first!</p>

    {% endif %}
{% endblock %}

templates/frontend/configurations.html
{% extends 'frontend/base.html' %}

{% block content %}

    <h1>Configurations</h1>


<div id="tabs">

<ul>
    <li><a href="#tab-configs">Configurations</a></li>
    <li><a href="{% url 'frontend:create_configuration' %}">Create</a></li>
</ul>



    <div id="tab-configs">
    <ul>
    {% for config in configs %}
        <li><a href="{% url 'frontend:edit_configuration' config=config.id %}">{{ config }}</a></li>
    {% endfor %}
    </ul>
    </div>
</div>
{% endblock %}

templates/frontend/create_configuration.html
<form action="{% url 'frontend:create_configuration' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="Submit" value="Submit"/>
</form>

<script>
        $("select[multiple=\"multiple\"]").multiSelect({
        selectableHeader: "<div class='select_header'>Available</div>",
        selectionHeader: "<div class='select_header'>Selected</div>",
    });
</script>

templates/frontend/create_device.html
<form action="{% url 'frontend:create_device' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="Submit" value="Submit"/>
</form>

<script>
        $("select[multiple=\"multiple\"]").multiSelect({
        selectableHeader: "<div class='select_header'>Available</div>",
        selectionHeader: "<div class='select_header'>Selected</div>",
    });
</script>

templates/frontend/create_stream.html
<form action="{% url 'frontend:create_stream' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="Submit" value="Submit"/>
</form>

templates/frontend/device_groups.html
{% extends 'frontend/base.html' %}

{% block content %}

    <h1>Device Groups</h1>


<div id="tabs">

<ul>
    <li><a href="#tab-groups">Groups</a></li>
    <li><a href="{% url 'frontend:create_device_group' %}">Create</a></li>
</ul>



    <div id="tab-groups">
    <ul>
    {% for group in groups %}
        <li><a href="{% url 'frontend:edit_device_group' grp=group.id %}">{{ group }}</a></li>
    {% endfor %}
    </ul>
    </div>
</div>
{% endblock %}

templates/frontend/devices.html
{% extends 'frontend/base.html' %}

{% block content %}

    <h1>Devices</h1>


    <div id="tabs">

        <ul>
            <li><a href="#tab-devices">Devices</a></li>
            <li><a href="{% url 'frontend:create_device' %}">Create</a></li>
        </ul>


        <div id="tab-devices">
            <ul>
                {% for device in devices %}
                    <li><a href="{% url 'frontend:edit_device' dev=device.id %}">{{ device }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

templates/frontend/edit_device.html
{% extends 'frontend/base.html' %}

{% block content %}
    <h1>Edit Device</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="Submit" value="Submit"/>
    </form>

{% endblock %}

templates/frontend/edit_device_group.html
{% extends 'frontend/base.html' %}

{% block content %}
    <h1>Edit Device Group</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="Submit" value="Submit"/>
    </form>

{% endblock %}

templates/frontend/edit_slideshow.html
{% extends 'frontend/base.html' %}

{% block content %}
    <h1>Edit Slideshow</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <a href="{% url 'frontend:slideshow' name=name %}" style="display: block;" target="_blank">View</a>
        <a href="{% url 'frontend:delete_slideshow' name=name %}" style="display: block;">Delete</a>
        <input type="Submit" value="Submit"/>
    </form>

{% endblock %}

templates/frontend/index.html
{% extends "frontend/base.html" %}

{% block content %}
    <h1>Status</h1>

    <ul>
    <li>Devices: {{ devices }}</li>
    <li>Device Groups: {{ groups }}</li>
    </ul>

{% endblock %}

templates/frontend/slideshow.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<!--
# Simple canvas-based slideshow capable of playing audio
#
# Author:   Dr. Mike Murphy <mmurphy2@coastal.edu>
# Revision: 5 February 2016
#
# Copyright 2016 Coastal Carolina University
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
-->

<head>
<link rel="stylesheet" type="text/css" href="{% static 'frontend/slideshow/css/style.css' %}">
<script src="{% static 'frontend/slideshow/js/jquery-2.2.0.min.js' %}"></script>
<script src="{% static 'frontend/slideshow/js/canvas.js' %}"></script>
<script src="{% static 'frontend/slideshow/js/media.js' %}"></script>
<script src="{% static 'frontend/slideshow/js/slideshow.js' %}"></script>
</head>

<body onresize="resize_canvas('render_area')">
<canvas id="render_area"></canvas>

<script>
$(document).ready(function(){
	resize_canvas("render_area");
	$.getJSON("{{ url }}", function(data) {
		SlideShow.slideset = data;
		SlideShow.canvas_id = "render_area";
		SlideShow.sound_id = "audio_set";
        resize_canvas("render_area");
		preload_slide();
	});
});
</script>
</body>

</html>

templates/frontend/slideshows.html
{% extends 'frontend/base.html' %}

{% block content %}

    <h1>Slideshows</h1>


    <div id="tabs">

        <ul>
            <li><a href="#tab-slideshows">Slideshows</a></li>
            <li><a href="{% url 'frontend:create_slideshow' %}">Create</a></li>
        </ul>


        <div id="tab-slideshows">
            <ul>
                {% for slide in slides %}
                    <li><a href="{% url 'frontend:edit_slideshow' name=slide %}">{{ slide }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

templates/frontend/streams.html
{% extends 'frontend/base.html' %}

{% block content %}

    <h1>Streams</h1>


    <div id="tabs">

        <ul>
            <li><a href="#tab-streams">Streams</a></li>
            <li><a href="{% url 'frontend:create_stream' %}">Create</a></li>
        </ul>


        <div id="tab-streams">
            <ul>
                {% for stream in streams %}
                    <li><a href="{% url 'frontend:edit_stream' name=stream %}">{{ stream }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}